/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pd;

/**
 *
 * @author Nati
 */

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class dep extends javax.swing.JFrame {

    /**
     * Creates new form dep
     */
    public Connection cn;
    public Statement st;
    
    public dep dep;
    public cases cases;
    public home home;
    public police police;
    public jail jail;
    public login login;
    
    public dep() {
        initComponents();
         this.setLocationRelativeTo(null);
         
         try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost/pd","root","");
            st = cn.createStatement();
           //JOptionPane.showMessageDialog(null, "Connected");
           System.out.println("connected");//this code block is only for cheacking if we are connected to the data base
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Not Connected");
        }
    }
    
    public Connection getConnection()
    {
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/pd", "root","");
            return con; 
        } catch (Exception e){
            e.printStackTrace();
            return null;
        }
    }
    
    
    public void executeSQLQuery(String query, String message)
    {
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
              JOptionPane.showMessageDialog(null, "Data "+message+"Succefully");
            }else{
                JOptionPane.showMessageDialog(null, "Data Not"+message);
            }
        } catch (Exception e) {
            e.printStackTrace(); 
        }
    }
    
    public void executeSQLQuery(String query)
    {
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            st.executeUpdate(query);
            
        } catch (Exception e) {
            e.printStackTrace(); 
        }
    }
    
    
    public Integer insertQueryGetId(String query){
        Integer numero=0;
        Integer risultato=-1;
        Connection con = getConnection();
        try{
            Statement stmt = con.createStatement();
            numero = stmt.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
            
            ResultSet rs = stmt.getGeneratedKeys();
            if(rs.next()){
                risultato= rs.getInt(1);
            }
            rs.close();
            
            stmt.close();
        }catch (Exception e){
            e.printStackTrace();
            risultato=-1;
        }
        return risultato;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dep_option = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        police_list = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        police_list_table4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(54, 33, 89));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("SPD V1.0");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(65, 43, 101));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Log out");

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shutdown_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 220, 50));

        jPanel12.setBackground(new java.awt.Color(65, 43, 101));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("jail");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Jail Doors With Bars_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 40));

        jPanel10.setBackground(new java.awt.Color(65, 43, 101));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Police");

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Policeman Male_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 40));

        jPanel9.setBackground(new java.awt.Color(65, 43, 101));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Cases");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Folder_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 40));

        jPanel8.setBackground(new java.awt.Color(54, 33, 89));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Departement");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Police Badge_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 40));

        jPanel3.setBackground(new java.awt.Color(65, 43, 101));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Home");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        dep_option.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(133, 83, 226));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fringe");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel16)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dep_option.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 630, -1));

        jPanel13.setBackground(new java.awt.Color(133, 83, 226));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Homicide");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel17)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dep_option.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 630, -1));

        jPanel14.setBackground(new java.awt.Color(133, 83, 226));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Robbery");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel18)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dep_option.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 630, -1));

        jPanel15.setBackground(new java.awt.Color(133, 83, 226));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Juvenile");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel19)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        dep_option.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 630, -1));

        jPanel16.setBackground(new java.awt.Color(133, 83, 226));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Narcotics");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel20)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dep_option.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 630, -1));

        jPanel17.setBackground(new java.awt.Color(133, 83, 226));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Traffic");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel21)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dep_option.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 630, -1));

        jPanel4.add(dep_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 18, 650, 530));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel9)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 650, 20));

        police_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        police_list_table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Badge Number", "Rank"
            }
        ));
        police_list_table4.setGridColor(new java.awt.Color(255, 255, 255));
        police_list_table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                police_list_table4MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(police_list_table4);

        police_list.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 530));

        jPanel4.add(police_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 650, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
         home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        dep = new dep();
        dep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        cases = new cases();
        cases.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
        police = new police();
        police.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
        jail = new jail();
        jail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)police_list_table4.getModel();
                model.setRowCount(0);
        dep_option.setVisible(false);
        police_list.setVisible(true);
        
        police_list_table4.setVisible(true);
        //departement.setVisible(false);
        //q = "Electrical";
      
        ArrayList<policeClass> policeList = new ArrayList<policeClass>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        String query = "SELECT badge_no , first_name , last_name , rank FROM npolice NATURAL JOIN police WHERE `department_id` = 0";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            policeClass pol;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                pol = new policeClass(rs.getString("first_name"),rs.getString("last_name"),rs.getInt("badge_no"),rs.getString("rank"));
                policeList.add(pol);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<policeClass> list = policeList;
        DefaultTableModel modell =(DefaultTableModel)police_list_table4.getModel();
        Object[] col = new Object[4];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getFname();    //the methods from the class user. which is what is done here
            col[1] = list.get(i).getLname();
            col[2] = list.get(i).getBadge();
            col[3] = list.get(i).getRank();
       
            model.addRow(col);     //this line of code will display the values to the jTable. since it's in a loop it will
        }   
    }//GEN-LAST:event_jPanel13MouseClicked

    private void police_list_table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_police_list_table4MouseClicked

    }//GEN-LAST:event_police_list_table4MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
           DefaultTableModel model = (DefaultTableModel)police_list_table4.getModel();
                model.setRowCount(0);
        dep_option.setVisible(false);
        police_list.setVisible(true);
        
        police_list_table4.setVisible(true);
        //departement.setVisible(false);
        //q = "Electrical";
      
        ArrayList<policeClass> policeList = new ArrayList<policeClass>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        String query = "SELECT badge_no , first_name , last_name , rank FROM npolice NATURAL JOIN police WHERE `department_id` = 1";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            policeClass pol;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                pol = new policeClass(rs.getString("first_name"),rs.getString("last_name"),rs.getInt("badge_no"),rs.getString("rank"));
                policeList.add(pol);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<policeClass> list = policeList;
        DefaultTableModel modell =(DefaultTableModel)police_list_table4.getModel();
        Object[] col = new Object[4];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getFname();    //the methods from the class user. which is what is done here
            col[1] = list.get(i).getLname();
            col[2] = list.get(i).getBadge();
            col[3] = list.get(i).getRank();
       
            model.addRow(col);     //this line of code will display the values to the jTable. since it's in a loop it will
        }   
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
             DefaultTableModel model = (DefaultTableModel)police_list_table4.getModel();
                model.setRowCount(0);
        dep_option.setVisible(false);
        police_list.setVisible(true);
        
        police_list_table4.setVisible(true);
        //departement.setVisible(false);
        //q = "Electrical";
      
        ArrayList<policeClass> policeList = new ArrayList<policeClass>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        String query = "SELECT badge_no , first_name , last_name , rank FROM npolice NATURAL JOIN police WHERE `department_id` = 2";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            policeClass pol;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                pol = new policeClass(rs.getString("first_name"),rs.getString("last_name"),rs.getInt("badge_no"),rs.getString("rank"));
                policeList.add(pol);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<policeClass> list = policeList;
        DefaultTableModel modell =(DefaultTableModel)police_list_table4.getModel();
        Object[] col = new Object[4];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getFname();    //the methods from the class user. which is what is done here
            col[1] = list.get(i).getLname();
            col[2] = list.get(i).getBadge();
            col[3] = list.get(i).getRank();
       
            model.addRow(col);     //this line of code will display the values to the jTable. since it's in a loop it will
        }   
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
        // TODO add your handling code here:
             DefaultTableModel model = (DefaultTableModel)police_list_table4.getModel();
                model.setRowCount(0);
        dep_option.setVisible(false);
        police_list.setVisible(true);
        
        police_list_table4.setVisible(true);
        //departement.setVisible(false);
        //q = "Electrical";
      
        ArrayList<policeClass> policeList = new ArrayList<policeClass>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        String query = "SELECT badge_no , first_name , last_name , rank FROM npolice NATURAL JOIN police WHERE `department_id` = 3";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            policeClass pol;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                pol = new policeClass(rs.getString("first_name"),rs.getString("last_name"),rs.getInt("badge_no"),rs.getString("rank"));
                policeList.add(pol);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<policeClass> list = policeList;
        DefaultTableModel modell =(DefaultTableModel)police_list_table4.getModel();
        Object[] col = new Object[4];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getFname();    //the methods from the class user. which is what is done here
            col[1] = list.get(i).getLname();
            col[2] = list.get(i).getBadge();
            col[3] = list.get(i).getRank();
       
            model.addRow(col);     //this line of code will display the values to the jTable. since it's in a loop it will
        }   
    }//GEN-LAST:event_jPanel16MouseClicked

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        // TODO add your handling code here:
             DefaultTableModel model = (DefaultTableModel)police_list_table4.getModel();
                model.setRowCount(0);
        dep_option.setVisible(false);
        police_list.setVisible(true);
        
        police_list_table4.setVisible(true);
        //departement.setVisible(false);
        //q = "Electrical";
      
        ArrayList<policeClass> policeList = new ArrayList<policeClass>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        String query = "SELECT badge_no , first_name , last_name , rank FROM npolice NATURAL JOIN police WHERE `department_id` = 4";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            policeClass pol;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                pol = new policeClass(rs.getString("first_name"),rs.getString("last_name"),rs.getInt("badge_no"),rs.getString("rank"));
                policeList.add(pol);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<policeClass> list = policeList;
        DefaultTableModel modell =(DefaultTableModel)police_list_table4.getModel();
        Object[] col = new Object[4];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getFname();    //the methods from the class user. which is what is done here
            col[1] = list.get(i).getLname();
            col[2] = list.get(i).getBadge();
            col[3] = list.get(i).getRank();
       
            model.addRow(col);     //this line of code will display the values to the jTable. since it's in a loop it will
        }   
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
             DefaultTableModel model = (DefaultTableModel)police_list_table4.getModel();
                model.setRowCount(0);
        dep_option.setVisible(false);
        police_list.setVisible(true);
        
        police_list_table4.setVisible(true);
        //departement.setVisible(false);
        //q = "Electrical";
      
        ArrayList<policeClass> policeList = new ArrayList<policeClass>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        String query = "SELECT badge_no , first_name , last_name , rank FROM npolice NATURAL JOIN police WHERE `department_id` = 5";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            policeClass pol;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                pol = new policeClass(rs.getString("first_name"),rs.getString("last_name"),rs.getInt("badge_no"),rs.getString("rank"));
                policeList.add(pol);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<policeClass> list = policeList;
        DefaultTableModel modell =(DefaultTableModel)police_list_table4.getModel();
        Object[] col = new Object[4];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getFname();    //the methods from the class user. which is what is done here
            col[1] = list.get(i).getLname();
            col[2] = list.get(i).getBadge();
            col[3] = list.get(i).getRank();
       
            model.addRow(col);     //this line of code will display the values to the jTable. since it's in a loop it will
        }   
    }//GEN-LAST:event_jPanel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dep_option;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel police_list;
    private javax.swing.JTable police_list_table4;
    // End of variables declaration//GEN-END:variables
}
