/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pd;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nati
 */
public class jail extends javax.swing.JFrame {

    /**
     * Creates new form jail
     */
    public Connection cn;
    public Statement st;
    
    public String caseNo;
    public String badgeNo;
    public String accused_id;
    public String detainee_id;
    
    public dep dep;
    public cases cases;
    public home home;
    public police police;
    public jail jail;
    public login login;
    
    public jail() {
        initComponents();
         this.setLocationRelativeTo(null);
         
         try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost/pd","root","");
            st = cn.createStatement();
           //JOptionPane.showMessageDialog(null, "Connected");
           System.out.println("connected");//this code block is only for cheacking if we are connected to the data base
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Not Connected");
        }
    }
    
    public Connection getConnection()
    {
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/pd", "root","");
            return con; 
        } catch (Exception e){
            e.printStackTrace();
            return null;
        }
    }
    
     public void executeSQLQuery(String query, String message)
    {
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
                
                DefaultTableModel model = (DefaultTableModel)police_list_table2.getModel();
                model.setRowCount(0);
               
                JOptionPane.showMessageDialog(null, "Data "+message+"Succefully");
            }else{
                JOptionPane.showMessageDialog(null, "Data Not"+message);
            }
        } catch (Exception e) {
            e.printStackTrace(); 
        }
    }
    
    public void executeSQLQuery(String query)
    {
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            st.executeUpdate(query);
            
        } catch (Exception e) {
            e.printStackTrace(); 
        }
    }
    
    
    public Integer insertQueryGetId(String query){
        Integer numero=0;
        Integer risultato=-1;
        Connection con = getConnection();
        try{
            Statement stmt = con.createStatement();
            numero = stmt.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
            
            ResultSet rs = stmt.getGeneratedKeys();
            if(rs.next()){
                risultato= rs.getInt(1);
            }
            rs.close();
            
            stmt.close();
        }catch (Exception e){
            e.printStackTrace();
            risultato=-1;
        }
        return risultato;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jail_option = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        accused_list = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detained_list_table = new javax.swing.JTable();
        detained_list = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detainee_list_table = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        cell_list = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        police_list = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        police_list_table2 = new javax.swing.JTable();
        jPanel36 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(54, 33, 89));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("SPD V1.0");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(65, 43, 101));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Log out");

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shutdown_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 220, 50));

        jPanel12.setBackground(new java.awt.Color(54, 33, 89));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("jail");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Jail Doors With Bars_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 40));

        jPanel10.setBackground(new java.awt.Color(65, 43, 101));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Police");

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Policeman Male_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 40));

        jPanel9.setBackground(new java.awt.Color(65, 43, 101));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel9KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Cases");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Folder_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 40));

        jPanel8.setBackground(new java.awt.Color(65, 43, 101));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Departement");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Police Badge_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 40));

        jPanel3.setBackground(new java.awt.Color(65, 43, 101));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Home");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        jail_option.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(133, 83, 226));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Detained");

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Prisoner_50px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(17, 17, 17)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jail_option.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 400, 120));

        jPanel13.setBackground(new java.awt.Color(133, 83, 226));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Check-in");

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Handcuffs_48px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel17)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(171, 171, 171))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jail_option.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 400, 120));

        jPanel4.add(jail_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 18, 650, 530));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel9)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 650, 20));

        accused_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(133, 83, 226));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Arrested by");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(65, 65, 65))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        accused_list.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 250, 40));

        detained_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accused Id", "First Name", "Last Name"
            }
        ));
        detained_list_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detained_list_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(detained_list_table);

        accused_list.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 490));

        jPanel4.add(accused_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 18, 650, 530));

        detained_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detainee_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Detainee Id", "Cell Number"
            }
        ));
        detainee_list_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detainee_list_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(detainee_list_table);

        detained_list.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 470));

        jPanel6.setBackground(new java.awt.Color(133, 83, 226));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Release");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel21)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel21)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        detained_list.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 160, 50));

        jPanel4.add(detained_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 18, 650, 530));

        cell_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(133, 83, 226));

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Choose a cell ");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(191, 191, 191))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        cell_list.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 510, 30));

        jPanel20.setBackground(new java.awt.Color(133, 83, 226));
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel20MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/9_52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel35)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel35)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cell_list.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 140, 120));

        jPanel21.setBackground(new java.awt.Color(133, 83, 226));
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1_52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel36)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel36)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cell_list.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 140, 120));

        jPanel22.setBackground(new java.awt.Color(133, 83, 226));
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel22MouseClicked(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2_52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel37)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel37)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cell_list.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 140, 120));

        jPanel23.setBackground(new java.awt.Color(133, 83, 226));
        jPanel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel23MouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3_52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel38)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel38)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cell_list.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 140, 120));

        jPanel24.setBackground(new java.awt.Color(133, 83, 226));
        jPanel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel24MouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4_52px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel39)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel39)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cell_list.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 120));

        jPanel25.setBackground(new java.awt.Color(133, 83, 226));
        jPanel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel25MouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5_52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel40)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel40)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cell_list.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 140, 120));

        jPanel26.setBackground(new java.awt.Color(133, 83, 226));
        jPanel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel26MouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/6_52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel41)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel41)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cell_list.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 140, 120));

        jPanel27.setBackground(new java.awt.Color(133, 83, 226));
        jPanel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel27MouseClicked(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/7_52px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel42)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel42)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        cell_list.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 140, 120));

        jPanel28.setBackground(new java.awt.Color(133, 83, 226));
        jPanel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel28MouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/8_52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel43)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(29, 29, 29))
        );

        cell_list.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 140, 120));

        jPanel4.add(cell_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 18, 650, 530));

        police_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        police_list_table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Badge Number", "Rank"
            }
        ));
        police_list_table2.setGridColor(new java.awt.Color(255, 255, 255));
        police_list_table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                police_list_table2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(police_list_table2);

        police_list.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 470));

        jPanel36.setBackground(new java.awt.Color(133, 83, 226));
        jPanel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel36MouseClicked(evt);
            }
        });

        jLabel60.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Detain");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel60)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        police_list.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 270, 40));

        jPanel4.add(police_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 650, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        dep = new dep();
        dep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel9KeyPressed
        // TODO add your handling code here:
        cases = new cases();
        cases.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel9KeyPressed

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
        police = new police();
        police.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
        jail = new jail();
        jail.setVisible(true);
        this.dispose();
        
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        cases = new cases();
        cases.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel9MouseClicked

    private void police_list_table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_police_list_table2MouseClicked
        // TODO add your handling code here:
        int i = police_list_table2.getSelectedRow();

        TableModel model = police_list_table2.getModel();
        badgeNo = model.getValueAt(i,2).toString();
        
    }//GEN-LAST:event_police_list_table2MouseClicked

    private void jPanel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel36MouseClicked
        // TODO add your handling code here:
        if(badgeNo != null && !(badgeNo.isEmpty())){
       java.util.Date dt = new java.util.Date();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String currentTime = sdf.format(dt);
        
      // here
      String queryyy = "INSERT INTO `police_arrests_accused`(`badge_no`, `accused_id`, `follow_date`) VALUES ('"+badgeNo+"','"+accused_id+"','"+currentTime+"')";
      //INSERT INTO `police_arrests_accused`(`badge_no`, `accused_id`, `follow_date`) VALUES ([value-1],[value-2],[value-3])
       executeSQLQuery(queryyy);
       jail_option.setVisible(false);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(true);
        police_list.setVisible(false);
        }else
            JOptionPane.showMessageDialog(null, "please select arresting officer");
    }//GEN-LAST:event_jPanel36MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modell = (DefaultTableModel)detained_list_table.getModel();
        modell.setRowCount(0);
        badgeNo = null;
        accused_id = null;
        
        jail_option.setVisible(false);
        accused_list.setVisible(true);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
        //departement.setVisible(false);
        //q = "Electrical";
      
        ArrayList<accused> accusedList = new ArrayList<accused>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        String query = "SELECT accused_id , first_name , last_name FROM naccused NATURAL JOIN accused";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            accused acc;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                acc = new accused(rs.getInt("accused_id"),rs.getString("first_name"),rs.getString("last_name"));
                accusedList.add(acc);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<accused> list = accusedList;
        DefaultTableModel model =(DefaultTableModel)detained_list_table.getModel();
        Object[] col = new Object[4];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getAccused_id();
            col[1] = list.get(i).getFname();    //the methods from the class user. which is what is done here
            col[2] = list.get(i).getLname();
            model.addRow(col);     //this line of code will display the values to the jTable. since it's in a loop it will
        }   
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
        if(accused_id != null && !(accused_id.isEmpty())){
           DefaultTableModel modell = (DefaultTableModel)police_list_table2.getModel();
        modell.setRowCount(0); 
        
           ArrayList<policeClass> policeList = new ArrayList<policeClass>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        String query = "SELECT badge_no , first_name , last_name , rank FROM npolice NATURAL JOIN police";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            policeClass pol;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                pol = new policeClass(rs.getString("first_name"),rs.getString("last_name"),rs.getInt("badge_no"),rs.getString("rank"));
                policeList.add(pol);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<policeClass> list = policeList;
        DefaultTableModel model =(DefaultTableModel)police_list_table2.getModel();
        Object[] col = new Object[4];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getFname();    //the methods from the class user. which is what is done here
            col[1] = list.get(i).getLname();
            col[2] = list.get(i).getBadge();
            col[3] = list.get(i).getRank();
       
            model.addRow(col);       
        }    
        
        jail_option.setVisible(false);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(true);
    }                                      
         else
            JOptionPane.showMessageDialog(null, "please select detainee.");
    
    }//GEN-LAST:event_jPanel11MouseClicked

    private void detained_list_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detained_list_tableMouseClicked
        // TODO add your handling code here:
         int i = detained_list_table.getSelectedRow();

        TableModel model = detained_list_table.getModel();
        accused_id = model.getValueAt(i,0).toString();
    }//GEN-LAST:event_detained_list_tableMouseClicked

    private void jPanel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21MouseClicked
        // TODO add your handling code here:
        /*int foo = Integer.parseInt(accused_id);
        String query = "SELECT `accused_id` FROM `detainee` WHERE `accused_id` = "+foo+"";
         Connection connection = getConnection(); 
        st = connection.createStatement(); //and question from the data base and send it to another class called user.
         rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            accused acc;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())  
        
        String queryyy = "INSERT INTO `detainee`(`accused_id`, `cell_no`) VALUES ("+foo+","+1+")";
        executeSQLQuery(queryyy);
       
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);*/
    }//GEN-LAST:event_jPanel21MouseClicked

    private void jPanel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseClicked
        // TODO add your handling code here:
          int foo = Integer.parseInt(accused_id);
        String queryyy = "INSERT INTO `detainee`(`accused_id`, `cell_no`) VALUES ("+foo+","+2+")";
        executeSQLQuery(queryyy);
       
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
    }//GEN-LAST:event_jPanel22MouseClicked

    private void jPanel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel23MouseClicked
        // TODO add your handling code here:
          int foo = Integer.parseInt(accused_id);
        String queryyy = "INSERT INTO `detainee`(`accused_id`, `cell_no`) VALUES ("+foo+","+3+")";
        executeSQLQuery(queryyy);
       
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
    }//GEN-LAST:event_jPanel23MouseClicked

    private void jPanel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel24MouseClicked
        // TODO add your handling code here:
          int foo = Integer.parseInt(accused_id);
        String queryyy = "INSERT INTO `detainee`(`accused_id`, `cell_no`) VALUES ("+foo+","+4+")";
        executeSQLQuery(queryyy);
       
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
    }//GEN-LAST:event_jPanel24MouseClicked

    private void jPanel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel25MouseClicked
        // TODO add your handling code here:
          int foo = Integer.parseInt(accused_id);
        String queryyy = "INSERT INTO `detainee`(`accused_id`, `cell_no`) VALUES ("+foo+","+5+")";
        executeSQLQuery(queryyy);
       
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
    }//GEN-LAST:event_jPanel25MouseClicked

    private void jPanel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel26MouseClicked
        // TODO add your handling code here:
          int foo = Integer.parseInt(accused_id);
        String queryyy = "INSERT INTO `detainee`(`accused_id`, `cell_no`) VALUES ("+foo+","+6+")";
        executeSQLQuery(queryyy);
       
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
    }//GEN-LAST:event_jPanel26MouseClicked

    private void jPanel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel27MouseClicked
        // TODO add your handling code here:
          int foo = Integer.parseInt(accused_id);
        String queryyy = "INSERT INTO `detainee`(`accused_id`, `cell_no`) VALUES ("+foo+","+7+")";
        executeSQLQuery(queryyy);
       
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
    }//GEN-LAST:event_jPanel27MouseClicked

    private void jPanel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel28MouseClicked
        // TODO add your handling code here:
          int foo = Integer.parseInt(accused_id);
        String queryyy = "INSERT INTO `detainee`(`accused_id`, `cell_no`) VALUES ("+foo+","+8+")";
        executeSQLQuery(queryyy);
       
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
    }//GEN-LAST:event_jPanel28MouseClicked

    private void jPanel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseClicked
        // TODO add your handling code here:
          int foo = Integer.parseInt(accused_id);
        String queryyy = "INSERT INTO `detainee`(`accused_id`, `cell_no`) VALUES ("+foo+","+9+")";
        executeSQLQuery(queryyy);
       
        jail_option.setVisible(true);
        accused_list.setVisible(false);
        detained_list.setVisible(false);
        cell_list.setVisible(false);
        police_list.setVisible(false);
    }//GEN-LAST:event_jPanel20MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modell = (DefaultTableModel)detainee_list_table.getModel();
        modell.setRowCount(0);
        
      /*  String query = "SELECT naccused.first_name , naccused.last_name, accused.accused_id , detainee.cell_no \n" +
"FROM accused LEFT JOIN detainee\n" +
"ON accused.accused_id = detainee.accused_id\n" +
"LEFT JOIN naccused\n" +
"ON accused.address_id = naccused.address_id"; 
        */
        String query = "SELECT `accused_id`, `cell_no` FROM `detainee`";
   //SELECT `accused_id`, `cell_no`, `blood_test` FROM `detainee` WHERE 1
        badgeNo = null;
        accused_id = null;
        jail_option.setVisible(false);
        accused_list.setVisible(false);
        detained_list.setVisible(true);
        cell_list.setVisible(false);
        police_list.setVisible(false);
        //departement.setVisible(false);
        //q = "Electrical";
      
        ArrayList<detainee> detaineeList = new ArrayList<detainee>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        //String query = "SELECT accused_id , first_name , last_name FROM naccused NATURAL JOIN accused";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            detainee det;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                det = new detainee(rs.getInt("accused_id"),rs.getInt("cell_no"));
                detaineeList.add(det);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<detainee> list = detaineeList;
        DefaultTableModel model =(DefaultTableModel)detainee_list_table.getModel();
        Object[] col = new Object[2];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getAccused();
            col[1] = list.get(i).getCell_no();
            model.addRow(col);     //this line of code will display the values to the jTable. since it's in a loop it will
        }   
    }//GEN-LAST:event_jPanel7MouseClicked

    private void detainee_list_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detainee_list_tableMouseClicked
        // TODO add your handling code here:
        int i = detainee_list_table.getSelectedRow();

        TableModel model = detainee_list_table.getModel();
        detainee_id = model.getValueAt(i,0).toString();
   
    }//GEN-LAST:event_detainee_list_tableMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        if(detainee_id != null && !(detainee_id.isEmpty())){
            String quary = "DELETE FROM `detainee` WHERE accused_id = "+detainee_id+"";
            executeSQLQuery(quary,"deleted");
            
            DefaultTableModel modell = (DefaultTableModel)detainee_list_table.getModel();
        modell.setRowCount(0);
        
      /*  String query = "SELECT naccused.first_name , naccused.last_name, accused.accused_id , detainee.cell_no \n" +
"FROM accused LEFT JOIN detainee\n" +
"ON accused.accused_id = detainee.accused_id\n" +
"LEFT JOIN naccused\n" +
"ON accused.address_id = naccused.address_id"; 
        */
        String query = "SELECT `accused_id`, `cell_no` FROM `detainee`";
   //SELECT `accused_id`, `cell_no`, `blood_test` FROM `detainee` WHERE 1
        badgeNo = null;
        accused_id = null;
        jail_option.setVisible(false);
        accused_list.setVisible(false);
        detained_list.setVisible(true);
        cell_list.setVisible(false);
        police_list.setVisible(false);
        //departement.setVisible(false);
        //q = "Electrical";
      
        ArrayList<detainee> detaineeList = new ArrayList<detainee>();//watch this line of code closely , it's making an arrylist of 
        Connection connection = getConnection();          //objects from the user class
        //String query = "SELECT accused_id , first_name , last_name FROM naccused NATURAL JOIN accused";  //form this code the data form the table electrical are loded since the 
        Statement st;                                  //the electrical button is clicked
        ResultSet rs;
        
        try {                                  //what this line of code is doing is that , it retrives the 'number' , 'title' 
            st = connection.createStatement(); //and question from the data base and send it to another class called user.
            rs = st.executeQuery(query);       //class user takes all this data and store them in a private field (through a constractor)
            detainee det;                         //this is done to make it easier to make objects from that class and store them 
            while(rs.next())                   //In an array list
            {
                det = new detainee(rs.getInt("accused_id"),rs.getInt("cell_no"));
                detaineeList.add(det);         //this is the part where an array list of the user class objects are created
            }
        } catch (Exception e)
        {
            e.printStackTrace(); //this line of code is not important it is just used to display errors in console when they 
        }                        //occure
        
        ArrayList<detainee> list = detaineeList;
        DefaultTableModel model =(DefaultTableModel)detainee_list_table.getModel();
        Object[] col = new Object[2];
        for(int i = 0; i<list.size();i++)
        {
               //since this array list is a list of objects form the class user we can use 
            col[0] = list.get(i).getAccused();
            col[1] = list.get(i).getCell_no();
            model.addRow(col);     //this line of code will display the values to the jTable. since it's in a loop it will
        }   
        }else
            JOptionPane.showMessageDialog(null, "please select detainee.");
    }//GEN-LAST:event_jPanel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accused_list;
    private javax.swing.JPanel cell_list;
    private javax.swing.JPanel detained_list;
    private javax.swing.JTable detained_list_table;
    private javax.swing.JTable detainee_list_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jail_option;
    private javax.swing.JPanel police_list;
    private javax.swing.JTable police_list_table2;
    // End of variables declaration//GEN-END:variables
}
